module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
    siteUrl: `https://www.example.com`,
  },
  plugins: [
    {
      resolve: 'gatsby-plugin-robots-txt',
      options: {
        host: 'https://www.example.com',
        sitemap: 'https://www.example.com/sitemap.xml',
        policy: [
          { userAgent: 'libwww-perl', disallow: ['/'] },
          { userAgent: 'Rogerbot', disallow: ['/'] },
          { userAgent: 'Exabot', disallow: ['/'] },
          { userAgent: 'MJ12bot', disallow: ['/'] },
          { userAgent: 'Dotbot', disallow: ['/'] },
          { userAgent: 'Gigabot', disallow: ['/'] },
          { userAgent: 'AhrefsBot', disallow: ['/'] },
          { userAgent: 'BlackWidow', disallow: ['/'] },
          { userAgent: 'Bot\ mailto:craftbot@yahoo.com', disallow: ['/'] },
          { userAgent: 'ChinaClaw', disallow: ['/'] },
          { userAgent: 'Custo', disallow: ['/'] },
          { userAgent: 'DISCo', disallow: ['/'] },
          { userAgent: 'Download\ Demon', disallow: ['/'] },
          { userAgent: 'eCatch', disallow: ['/'] },
          { userAgent: 'EirGrabber', disallow: ['/'] },
          { userAgent: 'EmailSiphon', disallow: ['/'] },
          { userAgent: 'EmailWolf', disallow: ['/'] },
          { userAgent: 'Express\ WebPictures', disallow: ['/'] },
          { userAgent: 'ExtractorPro', disallow: ['/'] },
          { userAgent: 'EyeNetIE', disallow: ['/'] },
          { userAgent: 'FlashGet', disallow: ['/'] },
          { userAgent: 'GetRight', disallow: ['/'] },
          { userAgent: 'GetWeb!', disallow: ['/'] },
          { userAgent: 'Go!Zilla', disallow: ['/'] },
          { userAgent: 'Go-Ahead-Got-It', disallow: ['/'] },
          { userAgent: 'GrabNet', disallow: ['/'] },
          { userAgent: 'Grafula', disallow: ['/'] },
          { userAgent: 'HMView', disallow: ['/'] },
          { userAgent: 'HTTrack', disallow: ['/'] },
          { userAgent: 'Image\ Stripper', disallow: ['/'] },
          { userAgent: 'Image\ Sucker', disallow: ['/'] },
          { userAgent: 'Indy\ Library', disallow: ['/'] },
          { userAgent: 'InterGET', disallow: ['/'] },
          { userAgent: 'Internet\ Ninja', disallow: ['/'] },
          { userAgent: 'JetCar', disallow: ['/'] },
          { userAgent: 'JOC\ Web\ Spider', disallow: ['/'] },
          { userAgent: 'larbin', disallow: ['/'] },
          { userAgent: 'LeechFTP', disallow: ['/'] },
          { userAgent: 'Mass\ Downloader', disallow: ['/'] },
          { userAgent: 'MIDown\ tool', disallow: ['/'] },
          { userAgent: 'Mister\ PiX', disallow: ['/'] },
          { userAgent: 'Navroad', disallow: ['/'] },
          { userAgent: 'NearSite', disallow: ['/'] },
          { userAgent: 'NetAnts', disallow: ['/'] },
          { userAgent: 'NetSpider', disallow: ['/'] },
          { userAgent: 'Net\ Vampire', disallow: ['/'] },
          { userAgent: 'NetZIP', disallow: ['/'] },
          { userAgent: 'Octopus', disallow: ['/'] },
          { userAgent: 'Offline\ Explorer', disallow: ['/'] },
          { userAgent: 'Offline\ Navigator', disallow: ['/'] },
          { userAgent: 'PageGrabber', disallow: ['/'] },
          { userAgent: 'Papa\ Foto', disallow: ['/'] },
          { userAgent: 'pavuk', disallow: ['/'] },
          { userAgent: 'pcBrowser', disallow: ['/'] },
          { userAgent: 'RealDownload', disallow: ['/'] },
          { userAgent: 'ReGet', disallow: ['/'] },
          { userAgent: 'SeznamBot', disallow: ['/'] },
          { userAgent: 'SiteSnagger', disallow: ['/'] },
          { userAgent: 'SmartDownload', disallow: ['/'] },
          { userAgent: 'SuperBot', disallow: ['/'] },
          { userAgent: 'SuperHTTP', disallow: ['/'] },
          { userAgent: 'Surfbot', disallow: ['/'] },
          { userAgent: 'tAkeOut', disallow: ['/'] },
          { userAgent: 'Teleport\ Pro', disallow: ['/'] },
          { userAgent: 'VoidEYE', disallow: ['/'] },
          { userAgent: 'Web\ Image\ Collector', disallow: ['/'] },
          { userAgent: 'Web\ Sucker', disallow: ['/'] },
          { userAgent: 'WebAuto', disallow: ['/'] },
          { userAgent: 'WebCopier', disallow: ['/'] },
          { userAgent: 'WebFetch', disallow: ['/'] },
          { userAgent: 'WebGo\ IS', disallow: ['/'] },
          { userAgent: 'WebLeacher', disallow: ['/'] },
          { userAgent: 'WebReaper', disallow: ['/'] },
          { userAgent: 'WebSauger', disallow: ['/'] },
          { userAgent: 'Website\ eXtractor', disallow: ['/'] },
          { userAgent: 'Website\ Quester', disallow: ['/'] },
          { userAgent: 'WebStripper', disallow: ['/'] },
          { userAgent: 'WebWhacker', disallow: ['/'] },
          { userAgent: 'WebZIP', disallow: ['/'] },
          { userAgent: 'Wget', disallow: ['/'] },
          { userAgent: 'Widow', disallow: ['/'] },
          { userAgent: 'WWWOFFLE', disallow: ['/'] },
          { userAgent: 'Xaldon\ WebSpider', disallow: ['/'] },
          { userAgent: 'Zeus', disallow: ['/'] },
        ]
      }
    },
    `gatsby-plugin-sitemap`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // 'gatsby-plugin-offline',
  ],
}
